### ISSUE TITLE
wget of .ipynb R notebooks from github do not open

### ISSUE THREAD

**Issue by CVandiedonck** [plasmabio/template-r#1]
Hello @pierrepo

Some weird think we expereienced tonight with Sandrine and Clémence. Clémence had updated two notebooks on a Sandrine's repo on github. We didn't want to redeploy the corresponding environment on adenine. We used wget to download the updated notebooks. But they could not open:
![image (1)](https://user-images.githubusercontent.com/46525836/100916176-b0927a00-34d5-11eb-90d6-c47f11b987c8.png)

We restarted the environment but no change.
However, if we redeployed the environment on adenine with a new name, the notebooks present in the repo were correctly loaded.

Any idea?

**Comment by CVandiedonck** [comment]
Clémence noticed this could be a reformat in github:
https://github.com/jupyter/help/issues/171

**Comment by pierrepo** [comment]
When you provide a link to download a notebook, take great care to provide the link to the **raw** notebook not the view of the notebook through the GitHub website.
For instance, the notebook `example-notebook.ipynb` at the root of this repo should be downloaded with 
```
wget https://raw.githubusercontent.com/plasmabio/template-r/master/example-notebook.ipynb
```
and not
```
wget https://github.com/plasmabio/template-r/blob/master/example-notebook.ipynb
```
Here's a animation to show you how to get the url of raw file:

![Peek 02-12-2020 20-54](https://user-images.githubusercontent.com/733861/100924338-c6596c80-34e0-11eb-8247-e3678850b963.gif)

**Comment by CVandiedonck** [comment]
Fantastic!  We spent more than an hour trying to sort that out today. I am relieved there is an explanation and a solution!
