### ISSUE TITLE
Unabble to load some packages in Rstudio interface while it works on Jupyter Lab

### ISSUE THREAD

**Issue by CVandiedonck** [plasmabio/template-r#4]
# Bug:

**1.** When loading an environment with this template (and all other environments I tested with an R kernel), it is impossible in the RStudio interface to load **[tidyverse](https://tidyverse.tidyverse.org/)** package with the R console...

![Capture1](https://user-images.githubusercontent.com/46525836/163386316-eac86f4b-842b-4cdb-95a2-4478c48db456.PNG)

**2.** ...whereas there is not such issue using Jupyter Lab interface:

![Capture2](https://user-images.githubusercontent.com/46525836/163386448-c8741438-ca7a-442a-82ef-d0c9659630ac.PNG)

**3.** Similarly, when using the RStudio interface and a Rmardown file (cf. next paragraph), the error still occurs when running the chunk to load tidyverse
![image](https://user-images.githubusercontent.com/46525836/163392882-ef1089f2-0cc3-410a-a632-c0a9cf4cdf8a.png)
***Need mardown package to test this point*** cf https://github.com/CVandiedonck/template-r/tree/patch-2

**4.** But ***suprinsingly***, the error does not longer occur when knitting a .Rmd document. 
![image](https://user-images.githubusercontent.com/46525836/163393548-233f7824-4e5f-4d71-9e9c-061009a630a4.png)

**5.** The generated .html file is fine and the `sessionInfo()` command output shows tidyverse was well loaded (but readxl is not).
![Capture5](https://user-images.githubusercontent.com/46525836/163394282-5ee56ce9-f168-406a-8c53-80de89555b47.png)

# Description of the error and extension to other packages

The error indicates an issue when trying to load the **readxl** package which is part of the **tidyverse**  package. The same error occurs when trying to load this package on its own, as well as several other packages that are installed with this "tempalte-r" in the environment, some being very useful like devtools:
- bslib
- devtools
- isoland
- later
- pkgload
- promises
- rcpp
- rematch
- sass
- testhat
- vroom
- data.table

# Question @plasmabio/quantstack 
Is this an issue in Plasma, something missing in the configuration files of the template or an issue with the Ubuntu server?
For the server, I tried on different instances (adenine or uracile at Université Paris Cité) or the VM machine you granted us acess too. The screenshots were generated with this VM.

**Comment by pierrepo** [comment]
This issue might be related to this [discussion](https://discourse.jupyter.org/t/glibcxx-3-4-26-not-found-from-rstudio/7778) and this one "[libstdc++.so.6: version `GLIBCXX_3.4.26' not found on Linux](https://stackoverflow.com/questions/69288536/libstdc-so-6-version-glibcxx-3-4-26-not-found-on-linux)"

**Comment by pierrepo** [comment]
And this one "[libstdc++.so.6: version `GLIBCXX_3.4.26' not found on Linux](https://stackoverflow.com/questions/69288536/libstdc-so-6-version-glibcxx-3-4-26-not-found-on-linux)"

**Comment by pierrepo** [comment]
This bug is also obtained with `repo2docker`. I created the corresponding issue https://github.com/jupyterhub/repo2docker/issues/1153

For troubleshooting, these commands are useful:

```r
library(tidyverse)
sessionInfo()
Sys.getenv("LD_LIBRARY_PATH")
```

**Comment by jtpio** [comment]
I just checked with the latest `repo2docker` and the troubleshooting steps mentioned above, and it looks like it is working fine now?

![image](https://github.com/plasmabio/template-r/assets/591645/4c877035-2dbc-424a-ad14-c8175a259cd3)

So hopefully this issue will be fixed by https://github.com/plasmabio/plasma/pull/217, which updates to the latest `repo2docker` image.

**Comment by CVandiedonck** [comment]
Yes it is all fixed with the update of repo2docker. We checked this during the summer and forgot to close the issue. It has been working well since.
